import { Check, FileSignature, Paperclip } from 'lucide-react';
import type { AppData } from '../types';
type Props = { data: AppData; onUpdate: (data: AppData) => void; selectedJobId: string | null; selectJob: (id: string | null) => void };
const items = [['estimate', 'Estimate approved', 'Customer has accepted the project price and scope.'], ['contract', 'Contract signed', 'Signed agreement is attached to the job.'], ['completion', 'Completion signed off', 'Customer has accepted the completed work.']] as const;
export function Approvals({ data, onUpdate, selectedJobId, selectJob }: Props) {
  const job = data.jobs.find((item) => item.id === selectedJobId); const estimate = data.estimates.find((item) => item.jobId === selectedJobId); const docs = data.attachments.filter((item) => item.jobId === selectedJobId); const approvals = job?.approvals || {};
  function mark(key: keyof typeof approvals) { if (!job) return; onUpdate({ ...data, jobs: data.jobs.map((item) => item.id === job.id ? { ...item, approvals: { ...approvals, [key]: approvals[key] ? undefined : new Date().toISOString() } } : item) }); }
  return <section className="workspace approvals-page"><div className="section-heading"><div><span className="eyebrow">Customer workflow</span><h1>Approvals & Documents</h1><p>Keep customer decisions and job paperwork attached to the project.</p></div><select className="job-select" value={selectedJobId || ''} onChange={(event) => selectJob(event.target.value || null)}><option value="">Select a job</option>{data.jobs.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{job ? <><div className="card approval-summary"><div><span>Estimate value</span><strong>{estimate ? `$${estimate.totalPrice.toLocaleString()}` : 'No estimate'}</strong></div><div><span>Customer</span><strong>{data.customers.find((item) => item.id === job.customerId)?.name || 'Unknown'}</strong></div><div><span>Documents</span><strong>{docs.length}</strong></div></div><div className="change-order-grid"><div className="card"><div className="section-head"><div><h3><FileSignature size={18} /> Approval checklist</h3><span>Record each decision with a timestamp.</span></div></div><div className="approval-list">{items.map(([key, label, detail]) => <button className={`approval-item ${approvals[key] ? 'complete' : ''}`} key={key} onClick={() => mark(key)}><span>{approvals[key] ? <Check size={16} /> : '•'}</span><div><strong>{label}</strong><small>{approvals[key] ? `Recorded ${new Date(approvals[key]!).toLocaleString()}` : detail}</small></div></button>)}</div></div><div className="card"><div className="section-head"><div><h3><Paperclip size={18} /> Job documents</h3><span>Documents already attached to this job.</span></div></div>{docs.length ? <div className="document-list">{docs.map((doc) => <div key={doc.id}><strong>{doc.name}</strong><span>{doc.type} · {new Date(doc.createdAt).toLocaleDateString()}</span></div>)}</div> : <div className="empty-state"><Paperclip size={24} /><h3>No documents attached</h3><p>Add contracts, permits, receipts, and warranties from the job record.</p></div>}</div></div></> : <div className="card empty-state"><FileSignature size={26} /><h3>Select a job</h3><p>Choose a job to manage approvals and documents.</p></div>}</section>;
}
