import { PackageCheck, Plus, Truck } from 'lucide-react';
import { useState } from 'react';
import type { AppData, MaterialOrder, MaterialOrderStatus } from '../types';
import { uid } from '../lib';

type Props = { data: AppData; onUpdate: (data: AppData) => void; selectedJobId: string | null; selectJob: (id: string | null) => void };
const statuses: MaterialOrderStatus[] = ['Requested', 'Ordered', 'Delivered', 'Staged'];
export function MaterialFulfillment({ data, onUpdate, selectedJobId, selectJob }: Props) {
  const [material, setMaterial] = useState(''); const [quantity, setQuantity] = useState(''); const [unit, setUnit] = useState('bundle'); const [supplier, setSupplier] = useState('');
  const orders = data.materialOrders || []; const selected = orders.filter((order) => order.jobId === selectedJobId); const staged = selected.filter((order) => order.status === 'Staged').length;
  function addOrder() { if (!selectedJobId || !material.trim() || !quantity) return; const item: MaterialOrder = { id: uid(), jobId: selectedJobId, material: material.trim(), quantity: Number(quantity), unit, supplier: supplier.trim() || 'Supplier TBD', status: 'Requested', createdAt: new Date().toISOString() }; onUpdate({ ...data, materialOrders: [...orders, item] }); setMaterial(''); setQuantity(''); setSupplier(''); }
  function advance(item: MaterialOrder) { const next = statuses[Math.min(statuses.indexOf(item.status) + 1, statuses.length - 1)]; onUpdate({ ...data, materialOrders: orders.map((order) => order.id === item.id ? { ...order, status: next } : order) }); }
  return <section className="workspace fulfillment-page"><div className="section-heading"><div><span className="eyebrow">Job logistics</span><h1>Material Fulfillment</h1><p>Move materials from request to staged at the job site.</p></div><select className="job-select" value={selectedJobId || ''} onChange={(event) => selectJob(event.target.value || null)}><option value="">Select a job</option>{data.jobs.map((job) => <option key={job.id} value={job.id}>{job.title}</option>)}</select></div>{selectedJobId ? <><div className="metric-row"><div className="ui-metric"><span>Material lines</span><strong>{selected.length}</strong></div><div className="ui-metric"><span>Staged</span><strong>{staged}/{selected.length}</strong></div><div className="ui-metric"><span>Open requests</span><strong>{selected.filter((item) => item.status !== 'Staged').length}</strong></div></div><div className="change-order-grid"><div className="card"><div className="section-head"><div><h3><Plus size={17} /> Add material request</h3><span>Capture what the job needs before production starts.</span></div></div><div className="form-grid"><label className="field wide"><span>Material</span><input value={material} onChange={(event) => setMaterial(event.target.value)} placeholder="Landmark shingles, ice and water membrane" /></label><label className="field"><span>Quantity</span><input type="number" min="0" value={quantity} onChange={(event) => setQuantity(event.target.value)} placeholder="0" /></label><label className="field"><span>Unit</span><select value={unit} onChange={(event) => setUnit(event.target.value)}><option>bundle</option><option>roll</option><option>piece</option><option>sq</option><option>lf</option></select></label><label className="field wide"><span>Supplier</span><input value={supplier} onChange={(event) => setSupplier(event.target.value)} placeholder="Supplier or store" /></label></div><button onClick={addOrder} disabled={!material.trim() || !quantity}><Truck size={16} /> Add request</button></div><div className="card"><div className="section-head"><div><h3>Fulfillment queue</h3><span>{selected.length ? 'Advance each line as it moves through delivery.' : 'No material requests for this job.'}</span></div></div>{selected.length ? <div className="material-order-list">{selected.map((item) => <div className="material-order-item" key={item.id}><div><strong>{item.material}</strong><span>{item.quantity} {item.unit} · {item.supplier}</span></div><button className={`status-pill ${item.status === 'Staged' ? 'success' : ''}`} onClick={() => advance(item)}>{item.status}</button></div>)}</div> : <div className="empty-state"><PackageCheck size={24} /><h3>No material requests</h3><p>Add materials needed for this job.</p></div>}</div></div></> : <div className="card empty-state"><PackageCheck size={26} /><h3>Select a job</h3><p>Choose a job to manage its material fulfillment.</p></div>}</section>;
}
