import { ClipboardCheck, Check } from 'lucide-react';
import type { AppData } from '../types';

type Props = { data: AppData; onUpdate: (data: AppData) => void; selectedJobId: string | null; selectJob: (id: string | null) => void };
const steps = [['approved', 'Scope approved', 'Estimate and changes are confirmed.'], ['crew', 'Crew assigned', 'A field crew is assigned.'], ['materials', 'Materials staged', 'Materials are ready at the job site.'], ['scheduled', 'Start date confirmed', 'Customer and crew have a confirmed date.'], ['started', 'Work started', 'The crew has clocked time against the job.'], ['closeout', 'Ready for closeout', 'Final photos, cleanup, and sign-off are complete.']] as const;
export function ProductionPlan({ data, onUpdate, selectedJobId, selectJob }: Props) {
  const job = data.jobs.find((item) => item.id === selectedJobId); const crew = data.crews.find((item) => item.id === job?.crewId); const customer = data.customers.find((item) => item.id === job?.customerId); const checklist = job?.productionChecklist || {}; const completed = steps.filter(([key]) => checklist[key]).length;
  function toggle(key: string) { if (!job) return; onUpdate({ ...data, jobs: data.jobs.map((item) => item.id === job.id ? { ...item, productionChecklist: { ...checklist, [key]: !checklist[key] } } : item) }); }
  return <section className="workspace production-page"><div className="section-heading"><div><span className="eyebrow">Job execution</span><h1>Production Plan</h1><p>Keep the crew, materials, schedule, and closeout steps aligned.</p></div><select className="job-select" value={selectedJobId || ''} onChange={(event) => selectJob(event.target.value || null)}><option value="">Select a job</option>{data.jobs.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{job ? <><div className="card production-summary"><div><span>Customer</span><strong>{customer?.name || 'Unknown customer'}</strong></div><div><span>Crew</span><strong>{crew?.name || 'Unassigned'}</strong></div><div><span>Scheduled</span><strong>{job.scheduledFor || 'Not scheduled'}</strong></div><div><span>Progress</span><strong>{completed}/{steps.length} ready</strong></div></div><div className="card production-checklist"><div className="section-head"><div><h3><ClipboardCheck size={18} /> Production readiness</h3><span>Update milestones as the project moves through the field.</span></div></div>{steps.map(([key, label, detail], index) => <button className={`production-step ${checklist[key] ? 'complete' : ''}`} key={key} onClick={() => toggle(key)}><span className="step-number">{checklist[key] ? <Check size={16} /> : index + 1}</span><span><strong>{label}</strong><small>{detail}</small></span></button>)}</div></> : <div className="card empty-state"><ClipboardCheck size={26} /><h3>Select a job</h3><p>Choose a job to build its production plan.</p></div>}</section>;
}
