import { ChartNoAxesCombined, TrendingDown, TrendingUp } from 'lucide-react';
import type { AppData } from '../types';

type Props = { data: AppData; selectedJobId: string | null; selectJob: (id: string | null) => void };
const money = (value: number) => `$${Math.round(value).toLocaleString()}`;
export function Profitability({ data, selectedJobId, selectJob }: Props) {
  const job = data.jobs.find((item) => item.id === selectedJobId); const estimate = data.estimates.find((item) => item.jobId === selectedJobId); const changes = (data.changeOrders || []).filter((item) => item.jobId === selectedJobId && item.status === 'Approved'); const logs = data.timeLogs.filter((log) => log.crewId === job?.crewId); const laborMinutes = logs.flatMap((log) => log.entries).reduce((sum, entry) => sum + (entry.durationMinutes || 0), 0); const laborCost = laborMinutes / 60 * 35; const changeTotal = changes.reduce((sum, item) => sum + item.amount, 0); const revenue = (estimate?.totalPrice || 0) + changeTotal; const materialCost = estimate?.materialCost || 0; const estimatedLabor = estimate?.laborCost || 0; const actualCost = laborCost + materialCost; const margin = revenue ? (revenue - actualCost) / revenue * 100 : 0;
  return <section className="workspace profitability-page"><div className="section-heading"><div><span className="eyebrow">Financial control</span><h1>Job Profitability</h1><p>Compare expected job economics with recorded field costs.</p></div><select className="job-select" value={selectedJobId || ''} onChange={(event) => selectJob(event.target.value || null)}><option value="">Select a job</option>{data.jobs.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{job ? <><div className="metric-row"><div className="ui-metric"><span>Projected revenue</span><strong>{money(revenue)}</strong></div><div className="ui-metric"><span>Recorded cost</span><strong>{money(actualCost)}</strong></div><div className="ui-metric"><span>Projected margin</span><strong className={margin >= 30 ? 'positive-value' : 'negative-value'}>{margin.toFixed(1)}%</strong></div></div><div className="change-order-grid"><div className="card profitability-breakdown"><div className="section-head"><div><h3><ChartNoAxesCombined size={18} /> Job breakdown</h3><span>Revenue includes approved change orders.</span></div></div><div className="profit-line"><span>Original estimate</span><strong>{money(estimate?.totalPrice || 0)}</strong></div><div className="profit-line"><span>Approved change orders</span><strong>{money(changeTotal)}</strong></div><div className="profit-line"><span>Material cost</span><strong>{money(materialCost)}</strong></div><div className="profit-line"><span>Estimated labor cost</span><strong>{money(estimatedLabor)}</strong></div><div className="profit-line"><span>Recorded labor cost <small>({(laborMinutes / 60).toFixed(1)} hours at $35/hr)</small></span><strong>{money(laborCost)}</strong></div></div><div className="card"><div className="section-head"><div><h3>{margin >= 30 ? <TrendingUp size={18} /> : <TrendingDown size={18} />} Margin health</h3><span>Use actual crew time to catch jobs drifting off plan.</span></div></div><div className="profit-health"><strong>{margin.toFixed(1)}%</strong><p>{margin >= 30 ? 'This job is currently above the 30% target margin.' : 'This job is below the 30% target margin and needs review.'}</p></div></div></div></> : <div className="card empty-state"><ChartNoAxesCombined size={26} /><h3>Select a job</h3><p>Choose a job to review its profitability.</p></div>}</section>;
}
