import type { AppData, ProjectTask } from './types'

const taskSeed: ProjectTask[] = [
  {
    id: 'task-1',
    customerId: 'cust-1',
    jobId: 'job-1',
    title: 'Confirm shingle color with homeowner',
    details: 'Call Jennifer before ordering materials and confirm the final architectural shingle color choice.',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-03-25',
    assignee: 'Office',
    checklist: [
      { id: 'task-1-check-1', label: 'Call homeowner', done: true },
      { id: 'task-1-check-2', label: 'Update notes after confirmation', done: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    customerId: 'cust-2',
    jobId: 'job-2',
    title: 'Send repair appointment reminder',
    details: 'Text customer the evening before and confirm access around the vent stack area.',
    priority: 'Normal',
    status: 'To Do',
    dueDate: '2026-03-22',
    assignee: 'Office',
    checklist: [
      { id: 'task-2-check-1', label: 'Confirm appointment window', done: false },
      { id: 'task-2-check-2', label: 'Mention driveway access', done: false },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const seedData: AppData & { tasks: ProjectTask[] } = {
  companyProfile: {
    name: 'Your Roofing Company',
    shortName: 'YRC',
    tagline: 'Add your company details in Settings',
    city: '',
    phone: '',
    email: '',
    website: '',
  },
  customers: [
    { id: 'cust-1', name: 'Jennifer Mullins', phone: '519-555-1001', email: 'jennifer@example.com', address: '123 Maple Ridge Dr, Windsor, ON', notes: 'Possible full replacement. Wants quote this week.', leadStatus: 'Inspection Scheduled', source: 'Facebook' },
    { id: 'cust-2', name: 'Mark Pitre', phone: '519-555-1002', email: 'mark@example.com', address: '88 Seacliff Dr, Leamington, ON', notes: 'Leak around vent stack. Asked about insurance.', leadStatus: 'Estimate Sent', source: 'Referral' },
    { id: 'cust-3', name: 'Arianna Lopes', phone: '519-555-1003', email: 'arianna@example.com', address: '27 Front Rd, LaSalle, ON', notes: 'Storm damage inspection request.', leadStatus: 'New Lead', source: 'Website' },
  ],
  jobs: [
    { id: 'job-1', customerId: 'cust-1', title: 'Full replacement — asphalt shingles', status: 'In Progress', priority: 'High', scheduledFor: '2026-03-24', notes: 'Two-storey detached home. Crew Alpha assigned.', crewId: 'crew-1', createdAt: new Date().toISOString() },
    { id: 'job-2', customerId: 'cust-2', title: 'Leak repair + flashing review', status: 'Scheduled', priority: 'Normal', scheduledFor: '2026-03-23', notes: 'Bring matching shingles and vent materials.', crewId: 'crew-2', createdAt: new Date().toISOString() },
  ],
  estimates: [
    { id: 'est-1', jobId: 'job-1', squareFeet: 2400, squares: 24, materialCost: 8200, laborCost: 3400, totalPrice: 14012, overheadCost: 1200, profitMargin: 18, taxRate: 13, depositRequired: 30, scopeOfWork: 'Complete roof replacement including tear-off, disposal, underlayment, shingles, flashing, ventilation review, and cleanup.', warranty: '10 year workmanship warranty', timeline: '2 working days weather permitting', lineItems: [{ id: 'li-1', title: 'Architectural shingles', quantity: 24, unit: 'sq', unitPrice: 220, total: 5280 }, { id: 'li-2', title: 'Accessories + flashing', quantity: 1, unit: 'lot', unitPrice: 1600, total: 1600 }, { id: 'li-3', title: 'Labour + disposal', quantity: 1, unit: 'job', unitPrice: 4720, total: 4720 }] },
    { id: 'est-2', jobId: 'job-2', squareFeet: 680, squares: 7, materialCost: 2100, laborCost: 1100, totalPrice: 4746, overheadCost: 400, profitMargin: 15, taxRate: 13, depositRequired: 25, scopeOfWork: 'Repair vent stack leak area, replace damaged shingles, reseal penetrations, and inspect adjacent decking.', warranty: '2 year workmanship warranty', timeline: 'Half day to 1 day', lineItems: [{ id: 'li-4', title: 'Repair materials', quantity: 1, unit: 'lot', unitPrice: 2100, total: 2100 }, { id: 'li-5', title: 'Labour', quantity: 1, unit: 'job', unitPrice: 1100, total: 1100 }] },
  ],
  invoices: [{ id: 'inv-1', jobId: 'job-2', invoiceNumber: 'INV-2001', amount: 4746, paidAmount: 1500, balanceDue: 3246, status: 'Partial', dueDate: '2026-03-31', issuedDate: '2026-03-24', notes: 'Deposit received. Balance due on completion.' }],
  invoiceHistory: [],
  inspections: [{ id: 'insp-1', customerId: 'cust-1', roofType: 'Asphalt shingle', roofAge: '14 years', pitch: '6/12', stories: '2 storey', damageType: 'Shingle Damage', urgency: 'High', leakActive: false, deckingConcern: false, flashingConcern: true, ventilationConcern: true, insuranceClaim: false, summary: 'Rear slope showing granule loss, lifted tabs, and flashing wear around the chimney line.', recommendation: 'Proceed with full replacement quote, replace flashing details, and review attic ventilation during install.', measurements: { squares: 24, ridgeLength: 42, valleyLength: 18, eavesLength: 64, rakeLength: 40, wasteFactor: 10 }, roofPlanes: [{ id: 'plane-1', label: 'Front Main', length: 34, width: 14, pitch: '6/12', facet: 'Main slope' }, { id: 'plane-2', label: 'Rear Main', length: 34, width: 14, pitch: '6/12', facet: 'Main slope' }], photos: [], createdAt: new Date().toISOString() }],
  tasks: taskSeed,
  materialPrices: [
    { id: 'mat-shingles', label: 'Architectural shingles', unit: 'bundle', price: 48, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-starter', label: 'Starter strip', unit: 'bundle', price: 55, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-ridge-cap', label: 'Ridge cap', unit: 'bundle', price: 65, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-underlayment', label: 'Underlayment', unit: 'roll', price: 120, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-ice-water', label: 'Ice & water shield', unit: 'roll', price: 95, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-drip-edge', label: 'Drip edge', unit: 'piece', price: 18, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-valley-metal', label: 'Valley metal', unit: 'piece', price: 32, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-cap-vent', label: 'Cap vents', unit: 'piece', price: 45, supplier: 'Manual', updatedAt: new Date().toISOString() },
    { id: 'mat-ridge-vent', label: 'Ridge vent', unit: 'lf', price: 7.25, supplier: 'Manual', updatedAt: new Date().toISOString() },
  ],
  materialPriceHistory: [],
  crews: [
    {
      id: 'crew-1',
      name: 'Crew Alpha',
      crewLead: 'Matt',
      phone: '519-555-2201',
      email: 'crew.alpha@example.com',
      status: 'Active',
      notes: 'Main replacement crew',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'crew-2',
      name: 'Crew Repair Team',
      crewLead: 'Nina',
      phone: '519-555-2202',
      email: 'crew.repairs@example.com',
      status: 'Active',
      notes: 'Leak and flashing repairs',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  appointments: [
    {
      id: 'appt-1',
      customerId: 'cust-1',
      jobId: 'job-1',
      title: 'Job start - full replacement',
      type: 'Job Start',
      status: 'Scheduled',
      startAt: new Date(new Date().setHours(9, 0, 0, 0)).toISOString(),
      endAt: new Date(new Date().setHours(13, 0, 0, 0)).toISOString(),
      location: '123 Maple Ridge Dr, Windsor, ON',
      notes: 'Crew Alpha on site by 8:45 AM',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'appt-2',
      customerId: 'cust-3',
      title: 'Initial roof inspection',
      type: 'Inspection',
      status: 'Scheduled',
      startAt: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      endAt: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      location: '27 Front Rd, LaSalle, ON',
      notes: 'Bring drone and ladder setup',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  damages: [
    {
      id: 'damage-1',
      customerId: 'cust-1',
      jobId: 'job-1',
      category: 'Flashing Damage',
      severity: 'Moderate',
      description: 'Rear slope has lifted tabs and exposed fasteners near chimney flashing line.',
      location: 'Rear slope / chimney line',
      estimatedCost: 1800,
      linkedPhotoIds: [],
      materials: [
        { materialId: 'mat-shingles', quantity: 8 },
        { materialId: 'mat-ridge-cap', quantity: 2 },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
}
